# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_manga
    restart: unless-stopped
    # user: "${UID}:${GID}"
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    # depends_on:
    #   - db

  web:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: laravel_composer
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    entrypoint: ["composer"]
    # user: "${UID}:${GID}"

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_artisan
    entrypoint: ["php", "/var/www/artisan"]
    # entrypoint: ["artisan"]
    working_dir: /var/www
    volumes:
      - ./src:/var/www

# node:
#     image: node:22
#     container_name: laravel_node
#     working_dir: /var/www
#     volumes:
#       - ./src:/var/www
#     ports:
#       - "5173:5173"
#     networks:
#       - laravel
#     command: sh -c "npm install && npm run dev -- --host"

  node:
    image: node:22
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - "5173:5173" # penting supaya bisa diakses dari device lain
    networks:
      - laravel
    command: sh -c "npm install && npm run dev -- --host"
    restart: unless-stopped

networks:
  laravel:
    driver: bridge
