# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    # user: "${UID}:${GID}"
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    # depends_on:
    #   - db

  web:
    image: nginx:alpine
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: laravel_composer
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    entrypoint: ["composer"]
    # user: "${UID}:${GID}"

networks:
  laravel:
    driver: bridge
